eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Patientservice
          uri: http://localhost:9000
          predicates:
            - Path=/patient/**
        - id: AppointmentService
          uri: http://localhost:9002
          predicates:
            - Path=/appointment/**
        - id: DoctorService
          uri: http://localhost:9001
          predicates:
            - Path=/doctor/**
        - id: Prescription
          uri: http://localhost:9005
          predicates:
            - Path=/prescription/**