server:
  port: 9001
spring:
  application:
    name: Doctor Service
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  hikari:
    connection-timeout: 20000  # Timeout for a connection to be established (in ms)
    maximum-pool-size: 5       # Maximum number of connections in the pool
    minimum-idle: 1